server:
  port: 8088  
spring:
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12714640
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sql12714640
    password: N54eLb4BwP
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: 5gN9IulnT6BBFLvIF83Xf++BtUfB4ZYoaHy0A78zmB8=

logging.level.org.springframework.security: DEBUG


